### ISSUE TITLE
error BPL

### ISSUE THREAD

**Issue by parabole33** [TurboPack/PNGComponents#10]
hello

I'm newbie in C++ Builder . When i compile i have this error : [ilink32 Erreur] Fatal: Impossible d'ouvrir le fichier 'PNGSPEEDBUTTON.OBJ'

I don't know whats happen ?

With GetIt manager : nothing ...

I'm french !!!   

Thank you very much

Regard

**Comment by romankassebaum** [comment]
Hi, please make sure that the path containing the .hpp and .obj files is included in the "System Include Path" and the "Library Path". Both of them can be modified in the Tools/Options under Language>C++>Paths and Directories.

From what you wrote this path seems to be missing in the "Library Path" but is included in the "System Include Path", so you can take it from there. If you installed it via GetIt it will be a directory in the Catalog Repository (c:\Users\Public\Documents\Embarcadero\Studio\22.0\CatalogRepository).

**Comment by parabole33** [comment]
reCan you check the attachement ?Can you help me please ? I'm newbie !!Best regardenvoyé : 31 juillet 2022 à 22:37de : Roman Kassebaum ***@***.***>à : TurboPack/PNGComponents ***@***.***>cc : parabole33 ***@***.***>, Author ***@***.***>objet : Re: [TurboPack/PNGComponents] error BPL (Issue #10) Hi, please make sure that the path containing the .hpp and .obj files is included in the "System Include Path" and the "Library Path". Both of them can be modified in the Tools/Options under Language>C++>Paths and Directories.From what you wrote this path seems to be missing in the "Library Path" but is included in the "System Include Path", so you can take it from there. If you installed it via GetIt it will be a directory in the Catalog Repository (c:\Users\Public\Documents\Embarcadero\Studio\22.0\CatalogRepository).—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by romankassebaum** [comment]
Here is not a QA forum. If you like you can contact me directly via PM.
