### ISSUE TITLE
Access Violation on unit PngImageList.pas finalization

### ISSUE THREAD

**Issue by danidummer** [TurboPack/PNGComponents#11]
I'm using PNGComponents in Delphi from it's GetIt Package Manager (version 2021-11-28).

At PngImageList.pas unit finalization, there's a call (below) to free the patches made during runtime.

```
initialization

finalization
  MethodPatches.Free;

```
The problem happens when I instance a project that don't create any TPNGImageList during its lifetime.
Once the variable MethodPatches is only initialized in TPNGImageList class creation, if I didn't create any of it, the variable will remain NIL, causing access violation on finalization.

This needs a simple fix, only initializating and checking the variable before freeing, as below:

```
initialization
  MethodPatches := nil;

finalization
  If Assigned(MethodPatches) then FreeAndNil(MethodPatches);

```

If you could fix and provide it to official repo, it will help a lot.

Thanks,
Daniel Dummer

**Comment by romankassebaum** [comment]
Are you absolutely sure? The variable is initialized

```
var
  ImageListCount: Integer = 0;
  MethodPatches: TObjectList = nil;
```
and Free can be called for a nil instance.

```
procedure TObject.Free;
begin
  if Self <> nil then
    Destroy;
end;
```

**Comment by danidummer** [comment]
Sorry, I double checked and this is not exactly what is happening.

The problem is still in that MethodPatches.Free (more precisely, the consequences of leaving the object MethodPatches address assigned) on unit's finalization, but not as I've mention above.

What is happening is that, in some specific cenarios (which is my case), the finalization sequence could be inverted, calling PngImageList.pas unit finalization before than other units, where I can still have a TPNGImageList object active.

So, running PngImageList.pas unit finalization first, it will destroy MethodPatches, but, later, when my remaining unit (with a TPNGImageList object) will be destroyed, it will try to call RevertPatchedMethods, trying to free again the already disposed MethodPatches. And, then, the access violation happen.

The fix is still the same. Besides only call Free, change to FreeAndNil, so it will prevent from "double freeing" it.

```
finalization
  FreeAndNil(MethodPatches);

```

**Comment by romankassebaum** [comment]
Ah, I see. I wrote

```
finalization
  MethodPatches.Free;
  MethodPatches := nil;
```

since FreeAndNil is NilAndFree.

BTW, you can add PngImageList as last unit to the .dpr file, then it is unloaded as last unit.

**Comment by danidummer** [comment]
Thank you very much! 
And Merry Christmas to all!

**Comment by romankassebaum** [comment]
Many thanks and Merry Christmas to you!
