### ISSUE TITLE
Can't install :(

### ISSUE THREAD

**Issue by kazuser** [TurboPack/PNGComponents#13]
Can't install it via the GetIt:
![image](https://github.com/TurboPack/PNGComponents/assets/3335273/2e7a9ac1-eb9a-4c6d-90d6-9c785c90b827)

Can't install it manually:
![image](https://github.com/TurboPack/PNGComponents/assets/3335273/05ae7c65-5200-4f94-881f-9b532ecbf4bd)

![image](https://github.com/TurboPack/PNGComponents/assets/3335273/b5ecc9dc-be3d-4f6e-8ec5-0b987cf6d495)

![image](https://github.com/TurboPack/PNGComponents/assets/3335273/03b573b9-efd3-4472-b792-b10649d504c1)

Could you please help me?

**Comment by kazuser** [comment]
I installed this set from [UweRaabe](https://github.com/UweRaabe/PngComponents) 🥲

**Comment by romankassebaum** [comment]
I just merged with the version from Uwe Raabe.
