### ISSUE TITLE
Installation problem on C++Builder 10.3 Rio

### ISSUE THREAD

**Issue by infoEL** [TurboPack/PNGComponents#2]
Automatic installation via GetIt Packet Manager is finished without errors. But, after droping component on the form, building throws error; at first proper include and library paths are missing. After manually adding them, linker reports "Unable to open file 'PNGSPEEDBUTTON.OBJ'.
Updated C++ Builder installation from Rio 10.3.2 to 10.3.3, problem is the same. Tried to manually install package from this site, problem still exists.

Instructions for installation on your site are confusing:
library path: d:\PNGComponents\source (hpp files missing?)
include path: d:\PNGComponents\source\hpp\Win32\Debug  (directory does not exist)

**Comment by romankassebaum** [comment]
GetIt compiles the sources during installation and creates the hpp files in an explicit cpp directory. At last it sets a search path to this folder. This should solve the issue, but it is only available for 10.3.4.
